
const ACTION_TYPES = {
  FETCH_SONGS: 'FETCH_SONGS',
  CREATE_SONG: 'CREATE_SONG',
  UPDATE_SONG: 'UPDATE_SONG',
  DELETE_SONG: 'DELETE_SONG',
  FETCH_SONG_STATISTICS: 'FETCH_SONG_STATISTICS',
  FETCH_ARTIST_STATISTICS: 'FETCH_ARTIST_STATISTICS',
  FETCH_ALBUM_STATISTICS: 'FETCH_SONG_STATISTICS',
  FETCH_GENRE_STATISTICS: 'FETCH_SONG_STATISTICS',
}

export default ACTION_TYPES;